linters:
  enable:
    - errcheck
    - exhaustive
    - goconst
    - godox
    - gofmt
    - mnd
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
linters-settings:
  lll:
    line-length: 228
    tab-width: 8
